// react/src/pages/concepts/persistence/PersistenceLocalPage.tsx
import { useMemo, useRef } from "react";
import {
  IndexedDBSyncProvider,
  KritzelEditor,
  HTMLKritzelEditorElement,
  type KritzelSyncConfig,
} from "kritzel-react";
import { reactThemeLight } from "../../../const/react-theme-light";
import {
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from "../shared/concept-shared";

export function PersistenceLocalPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const syncConfig = useMemo<KritzelSyncConfig>(
    () => ({ providers: [IndexedDBSyncProvider] }),
    [],
  );

  return (
    <div style={{ ...hostStyle, background: "linear-gradient(180deg, #f3fbff 0%, #ffffff 100%)" }}>
      <div style={toolbarStyle}>
        <span style={{ fontWeight: 700, color: "#087ea4", fontSize: "13px" }}>Persistence Provider:</span>
        <span style={{ fontSize: "12px", color: "#065d7a" }}>IndexedDB enabled</span>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="persistence-local"
        syncConfig={syncConfig}
        theme="react-theme"
        themes={[reactThemeLight]}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          const editor = editorRef.current;
          if (!editor) {
            return;
          }

          void (async () => {
            const existing = await editor.getAllObjects();
            if (existing.length > 0) {
              return;
            }

            await seedEditor(editor);
          })();
        }}
        style={editorStyle}
      />
    </div>
  );
}

// vue/src/pages/concepts/persistence/PersistenceLocalPage.vue
<script setup lang="ts">

import {
  getEditorRef,
  IndexedDBSyncProvider,
  KritzelEditor,
  type KritzelSyncConfig,
} from 'kritzel-vue'
import { vueThemeLight } from '../../../const/vue-theme-light'
import {
  accentDark,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from '../shared/concept-shared'

const editor = getEditorRef('editor');

const syncConfig: KritzelSyncConfig = {
  providers: [IndexedDBSyncProvider],
}

async function onReady() {
  if (editor.value) {
    const existing = await editor.value.getAllObjects()
    if (existing.length > 0) {
      return
    }

    await seedEditor(editor.value)
  }
}
</script>

<template>
  <div :style="{ ...hostStyle, background: 'linear-gradient(180deg, #f3fbf8 0%, #ffffff 100%)' }">
    <div :style="toolbarStyle">
      <span :style="{ fontWeight: 700, color: accentDark, fontSize: '13px' }">Persistence Provider:</span>
      <span :style="{ fontSize: '12px', color: accentDark }">IndexedDB enabled</span>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="persistence-local"
      theme="vue-theme"
      :themes="[vueThemeLight]"
      :syncConfig="syncConfig"
      :loginConfig="undefined"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>
