// vue/src/pages/concepts/collaboration/CollaborationRealtimePage.vue
<script setup lang="ts">

import {
  getEditorRef,
  HocuspocusSyncProvider,
  IndexedDBSyncProvider,
  KritzelEditor,
  type KritzelSyncConfig,
} from 'kritzel-vue'
import { customVueTheme } from '../../../const/custom-vue-theme'
import {
  accentDark,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from '../shared/concept-shared'

const editor = getEditorRef('editor');

const syncConfig: KritzelSyncConfig = {
  providers: [
    IndexedDBSyncProvider,
    HocuspocusSyncProvider.with({ url: 'wss://your-hocuspocus-server.com' }),
  ],
}

async function onReady() {
  if (editor.value) {
    const existing = await editor.value.getAllObjects()
    if (existing.length > 0) {
      return
    }

    await seedEditor(editor.value)
  }
}
</script>

<template>
  <div :style="{ ...hostStyle, background: 'radial-gradient(circle at 0% 0%, #e8fbf3 0%, #ffffff 42%)' }">
    <div :style="toolbarStyle">
      <span :style="{ fontWeight: 700, color: accentDark, fontSize: '13px' }">Real-time Sync</span>
      <span :style="{ fontSize: '12px', color: accentDark }">Configured for Hocuspocus server</span>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="collaboration-realtime"
      theme="vue-theme"
      :themes="[customVueTheme]"
      :syncConfig="syncConfig"
      :loginConfig="undefined"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>

// react/src/pages/concepts/collaboration/CollaborationRealtimePage.tsx
import { useMemo, useRef } from "react";
import {
  HocuspocusSyncProvider,
  IndexedDBSyncProvider,
  KritzelEditor,
  HTMLKritzelEditorElement,
  type KritzelSyncConfig,
} from "kritzel-react";
import { customReactTheme } from "../../../const/custom-react-theme";
import {
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from "../shared/concept-shared";

export function CollaborationRealtimePage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const syncConfig = useMemo<KritzelSyncConfig>(
    () => ({
      providers: [
        IndexedDBSyncProvider,
        HocuspocusSyncProvider.with({ url: "wss://your-hocuspocus-server.com" }),
      ],
    }),
    [],
  );

  return (
    <div style={{ ...hostStyle, background: "radial-gradient(circle at 0% 0%, #e9f8ff 0%, #ffffff 42%)" }}>
      <div style={toolbarStyle}>
        <span style={{ fontWeight: 700, color: "#087ea4", fontSize: "13px" }}>Real-time Sync</span>
        <span style={{ fontSize: "12px", color: "#065d7a" }}>Configured for Hocuspocus server</span>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="collaboration-realtime"
        syncConfig={syncConfig}
        theme="react-theme"
        themes={[customReactTheme]}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          const editor = editorRef.current;
          if (!editor) {
            return;
          }

          void (async () => {
            const existing = await editor.getAllObjects();
            if (existing.length > 0) {
              return;
            }

            await seedEditor(editor);
          })();
        }}
        style={editorStyle}
      />
    </div>
  );
}
