// vue/src/pages/concepts/collaboration/CollaborationLocalPage.vue
<script setup lang="ts">

import {
  BroadcastSyncProvider,
  KritzelEditor,
  type KritzelSyncConfig,
} from 'kritzel-vue'
import { customVueTheme } from '../../../const/custom-vue-theme'
import {
  accentDark,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from '../shared/concept-shared'
import { ref } from 'vue'

const editor = ref<HTMLKritzelEditorElement | null>(null)

const syncConfig: KritzelSyncConfig = {
  providers: [BroadcastSyncProvider],
}

async function onReady() {
  if (editor.value) {
    await seedEditor(editor.value)
  }
}
</script>

<template>
  <div :style="{ ...hostStyle, background: 'linear-gradient(160deg, #e8fbf3 0%, #ffffff 46%)' }">
    <div :style="toolbarStyle">
      <span :style="{ fontWeight: 700, color: accentDark, fontSize: '13px' }">Cross-tab Sync</span>
      <span :style="{ fontSize: '12px', color: accentDark }">BroadcastChannel enabled</span>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="collaboration-local"
      theme="vue-theme"
      :themes="[customVueTheme]"
      :syncConfig="syncConfig"
      :loginConfig="undefined"
      :wheelEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>

// react/src/pages/concepts/collaboration/CollaborationLocalPage.tsx
import { useMemo, useRef } from "react";
import {
  BroadcastSyncProvider,
  KritzelEditor,
  type HTMLKritzelEditorElement,
  type KritzelSyncConfig,
} from "kritzel-react";
import { customReactTheme } from "../../../const/custom-react-theme";
import {
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from "../shared/concept-shared";

export function CollaborationLocalPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const syncConfig = useMemo<KritzelSyncConfig>(
    () => ({ providers: [BroadcastSyncProvider] }),
    [],
  );

  return (
    <div style={{ ...hostStyle, background: "linear-gradient(160deg, #e9f8ff 0%, #ffffff 46%)" }}>
      <div style={toolbarStyle}>
        <span style={{ fontWeight: 700, color: "#087ea4", fontSize: "13px" }}>Cross-tab Sync</span>
        <span style={{ fontSize: "12px", color: "#065d7a" }}>BroadcastChannel enabled</span>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="collaboration-local"
        wheelEnabled={false}
        syncConfig={syncConfig}
        theme="react-theme"
        themes={[customReactTheme]}
        loginConfig={undefined}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          if (editorRef.current) {
            void seedEditor(editorRef.current);
          }
        }}
        style={editorStyle}
      />
    </div>
  );
}
