// react/src/pages/concepts/custom-elements/TodoListComponent.tsx
import { useEffect, useMemo, useState, type CSSProperties, type FormEvent } from "react";

type TodoItem = {
  id: number;
  title: string;
  isCompleted: boolean;
};

export type TodoListState = {
  todos: TodoItem[];
  nextId: number;
};

const DEFAULT_TODO_STATE: TodoListState = {
  nextId: 4,
  todos: [
    { id: 1, title: "Review project docs", isCompleted: true },
    { id: 2, title: "Build a React custom element", isCompleted: false },
    { id: 3, title: "Verify renderer rehydration", isCompleted: false },
  ],
};

export function cloneTodoListState(state: TodoListState): TodoListState {
  return {
    nextId: state.nextId,
    todos: state.todos.map((todo) => ({ ...todo })),
  };
}

export function createTodoListInitialState(): TodoListState {
  return cloneTodoListState(DEFAULT_TODO_STATE);
}

type TodoListComponentProps = {
  initialState?: TodoListState;
  onStateChange?: (state: TodoListState) => void;
};

export function TodoListComponent({ initialState, onStateChange }: TodoListComponentProps) {
  const startingState = useMemo(
    () => cloneTodoListState(initialState ?? createTodoListInitialState()),
    [initialState],
  );

  const [todos, setTodos] = useState<TodoItem[]>(startingState.todos);
  const [nextId, setNextId] = useState<number>(startingState.nextId);
  const [newTodo, setNewTodo] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editValue, setEditValue] = useState("");

  useEffect(() => {
    onStateChange?.({ nextId, todos: todos.map((todo) => ({ ...todo })) });
  }, [nextId, onStateChange, todos]);

  const totalCount = todos.length;
  const doneCount = todos.filter((todo) => todo.isCompleted).length;
  const openCount = totalCount - doneCount;

  function addTodo(event: FormEvent) {
    event.preventDefault();
    const title = newTodo.trim();
    if (!title) {
      return;
    }

    const id = nextId;
    setTodos((current) => [...current, { id, title, isCompleted: false }]);
    setNextId((current) => current + 1);
    setNewTodo("");
  }

  function toggleTodo(todoId: number) {
    setTodos((current) =>
      current.map((todo) => (todo.id === todoId ? { ...todo, isCompleted: !todo.isCompleted } : todo)),
    );
  }

  function deleteTodo(todoId: number) {
    setTodos((current) => current.filter((todo) => todo.id !== todoId));
    if (editingId === todoId) {
      setEditingId(null);
      setEditValue("");
    }
  }

  function startEdit(todo: TodoItem) {
    setEditingId(todo.id);
    setEditValue(todo.title);
  }

  function cancelEdit() {
    setEditingId(null);
    setEditValue("");
  }

  function saveEdit(todoId: number, event: FormEvent) {
    event.preventDefault();
    const title = editValue.trim();
    if (!title) {
      return;
    }

    setTodos((current) => current.map((todo) => (todo.id === todoId ? { ...todo, title } : todo)));
    setEditingId(null);
    setEditValue("");
  }

  return (
    <section style={cardStyle}>
      <header>
        <h1 style={headingStyle}>Todo List</h1>
        <p style={subheadingStyle}>Simple React CRUD inside a Kritzel custom element</p>
      </header>

      <form style={createFormStyle} onSubmit={addTodo}>
        <label htmlFor="react-custom-element-new-todo" style={srOnlyStyle}>New todo</label>
        <input
          id="react-custom-element-new-todo"
          type="text"
          value={newTodo}
          onChange={(event) => setNewTodo(event.target.value)}
          placeholder="Add a new task"
          style={inputStyle}
        />
        <button type="submit" disabled={newTodo.trim().length === 0} style={primaryButtonStyle}>
          Add
        </button>
      </form>

      <section style={statsStyle} aria-live="polite">
        <span>Total: {totalCount}</span>
        <span>Open: {openCount}</span>
        <span>Done: {doneCount}</span>
      </section>

      {todos.length === 0 ? (
        <p style={emptyStateStyle}>No todos yet. Add your first task above.</p>
      ) : (
        <ul style={listStyle}>
          {todos.map((todo) => {
            const isEditing = editingId === todo.id;
            return (
              <li key={todo.id} style={{ ...itemStyle, ...(todo.isCompleted ? completedItemStyle : undefined) }}>
                {isEditing ? (
                  <form style={editFormStyle} onSubmit={(event) => saveEdit(todo.id, event)}>
                    <label htmlFor={`react-custom-element-edit-${todo.id}`} style={srOnlyStyle}>Edit todo</label>
                    <input
                      id={`react-custom-element-edit-${todo.id}`}
                      type="text"
                      value={editValue}
                      onChange={(event) => setEditValue(event.target.value)}
                      style={inputStyle}
                    />
                    <div style={actionsStyle}>
                      <button type="submit" disabled={editValue.trim().length === 0} style={secondaryButtonStyle}>Save</button>
                      <button type="button" onClick={cancelEdit} style={secondaryButtonStyle}>Cancel</button>
                    </div>
                  </form>
                ) : (
                  <div style={viewRowStyle}>
                    <label style={checkboxRowStyle}>
                      <input type="checkbox" checked={todo.isCompleted} onChange={() => toggleTodo(todo.id)} />
                      <span>{todo.title}</span>
                    </label>
                    <div style={actionsStyle}>
                      <button type="button" onClick={() => startEdit(todo)} style={secondaryButtonStyle}>Edit</button>
                      <button type="button" onClick={() => deleteTodo(todo.id)} style={secondaryButtonStyle}>Delete</button>
                    </div>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}

const cardStyle: CSSProperties = {
  width: "100%",
  height: "100%",
  boxSizing: "border-box",
  border: "1px solid #d5dbe8",
  borderRadius: "16px",
  padding: "20px",
  background: "#ffffff",
  overflow: "auto",
  fontFamily: "Roboto, sans-serif",
};

const headingStyle: CSSProperties = {
  margin: 0,
  fontSize: "2rem",
  color: "#1b2440",
};

const subheadingStyle: CSSProperties = {
  margin: "4px 0 0",
  color: "#4c5775",
};

const createFormStyle: CSSProperties = {
  marginTop: "16px",
  display: "grid",
  gridTemplateColumns: "1fr auto",
  gap: "8px",
};

const inputStyle: CSSProperties = {
  width: "100%",
  border: "1px solid #bfc8dc",
  borderRadius: "10px",
  padding: "10px 12px",
  fontSize: "0.98rem",
  boxSizing: "border-box",
};

const statsStyle: CSSProperties = {
  marginTop: "14px",
  display: "flex",
  gap: "12px",
  flexWrap: "wrap",
  color: "#334268",
  fontSize: "0.92rem",
};

const emptyStateStyle: CSSProperties = {
  margin: "18px 0 0",
  color: "#4f5b7b",
};

const listStyle: CSSProperties = {
  margin: "14px 0 0",
  padding: 0,
  listStyle: "none",
  display: "grid",
  gap: "10px",
};

const itemStyle: CSSProperties = {
  border: "1px solid #d7deee",
  borderRadius: "12px",
  padding: "10px",
  background: "#fbfcff",
};

const completedItemStyle: CSSProperties = {
  color: "#67718f",
  textDecoration: "line-through",
};

const viewRowStyle: CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: "8px",
};

const checkboxRowStyle: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  gap: "8px",
};

const actionsStyle: CSSProperties = {
  display: "inline-flex",
  gap: "6px",
};

const editFormStyle: CSSProperties = {
  display: "grid",
  gap: "8px",
};

const primaryButtonStyle: CSSProperties = {
  border: "1px solid #245f8f",
  borderRadius: "10px",
  padding: "10px 14px",
  fontWeight: 600,
  color: "#ffffff",
  background: "#2b73ad",
  cursor: "pointer",
};

const secondaryButtonStyle: CSSProperties = {
  border: "1px solid #9fb0d0",
  borderRadius: "10px",
  padding: "7px 10px",
  fontWeight: 500,
  color: "#2d3b5e",
  background: "#f4f7ff",
  cursor: "pointer",
};

const srOnlyStyle: CSSProperties = {
  position: "absolute",
  width: "1px",
  height: "1px",
  padding: 0,
  margin: "-1px",
  overflow: "hidden",
  clip: "rect(0, 0, 0, 0)",
  border: 0,
};

// angular/src/app/concepts/custom-elements/todo-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  signal,
} from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';

interface TodoItem {
  id: number;
  title: string;
  isCompleted: boolean;
}

export interface TodoListState {
  todos: TodoItem[];
  nextId: number;
}

const DEFAULT_TODO_STATE: TodoListState = {
  nextId: 4,
  todos: [
    { id: 1, title: 'Review project docs', isCompleted: true },
    { id: 2, title: 'Build a standalone component', isCompleted: false },
    { id: 3, title: 'Verify route integration', isCompleted: false },
  ],
};

export function createTodoListInitialState(): TodoListState {
  return {
    nextId: DEFAULT_TODO_STATE.nextId,
    todos: DEFAULT_TODO_STATE.todos.map((todo) => ({ ...todo })),
  };
}

@Component({
  selector: 'app-todo-list',
  imports: [ReactiveFormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
  template: `
    <section class="todo-card">
      <header class="todo-header">
        <h1>Todo List</h1>
        <p>Simple Angular CRUD with signals</p>
      </header>

      <form class="create-form" (submit)="addTodo($event)">
        <label for="newTodo" class="sr-only">New todo</label>
        <input
          id="newTodo"
          type="text"
          [formControl]="newTodoControl"
          placeholder="Add a new task"
        />
        <button type="submit" [disabled]="newTodoControl.invalid">Add</button>
      </form>

      <section class="stats" aria-live="polite">
        <span>Total: {{ totalCount() }}</span>
        <span>Open: {{ openCount() }}</span>
        <span>Done: {{ doneCount() }}</span>
      </section>

      @if (todos().length === 0) {
        <p class="empty">No todos yet. Add your first task above.</p>
      } @else {
        <ul class="todo-list">
          @for (todo of todos(); track todo.id) {
            <li
              class="todo-item"
              [class.completed]="todo.isCompleted"
              [class.editing]="editingId() === todo.id"
            >
              @if (editingId() === todo.id) {
                <form class="edit-form" (submit)="saveEdit(todo.id, $event)">
                  <label [for]="'edit-' + todo.id" class="sr-only">Edit todo</label>
                  <input
                    [id]="'edit-' + todo.id"
                    type="text"
                    [formControl]="editControl"
                  />
                  <div class="actions">
                    <button type="submit" [disabled]="editControl.invalid">
                      Save
                    </button>
                    <button type="button" (click)="cancelEdit()">Cancel</button>
                  </div>
                </form>
              } @else {
                <div class="view-row">
                  <label class="checkbox-row">
                    <input
                      type="checkbox"
                      [checked]="todo.isCompleted"
                      (change)="toggleTodo(todo.id)"
                    />
                    <span>{{ todo.title }}</span>
                  </label>
                  <div class="actions">
                    <button type="button" (click)="startEdit(todo)">Edit</button>
                    <button type="button" (click)="deleteTodo(todo.id)">Delete</button>
                  </div>
                </div>
              }
            </li>
          }
        </ul>
      }
    </section>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
        height: 100%;
        min-width: 0;
        min-height: 0;
        box-sizing: border-box;
        border: 1px solid #d5dbe8;
        border-radius: 16px;
        padding: 20px;
        background: #ffffff;
        overflow: auto;
      }

      *,
      *::before,
      *::after {
        box-sizing: border-box;
      }

      .todo-card {
        width: 100%;
        min-height: 100%;
        margin: 0;
      }

      .todo-header h1 {
        margin: 0;
        font-size: 2rem;
        color: #1b2440;
      }

      .todo-header p {
        margin: 4px 0 0;
        color: #4c5775;
      }

      .create-form {
        margin-top: 16px;
        display: grid;
        grid-template-columns: 1fr auto;
        gap: 8px;
      }

      input[type='text'] {
        width: 100%;
        border: 1px solid #bfc8dc;
        border-radius: 10px;
        padding: 10px 12px;
        font-size: 0.98rem;
      }

      button {
        border: 1px solid #245f8f;
        border-radius: 10px;
        padding: 10px 14px;
        font-weight: 600;
        color: #ffffff;
        background: #2b73ad;
        cursor: pointer;
      }

      button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .stats {
        margin-top: 14px;
        display: flex;
        gap: 12px;
        flex-wrap: wrap;
        color: #334268;
        font-size: 0.92rem;
      }

      .empty {
        margin: 18px 0 0;
        color: #4f5b7b;
      }

      .todo-list {
        margin: 14px 0 0;
        padding: 0;
        list-style: none;
        display: grid;
        gap: 10px;
      }

      .todo-item {
        border: 1px solid #d7deee;
        border-radius: 12px;
        padding: 10px;
        background: #fbfcff;
      }

      .todo-item.completed .view-row span {
        text-decoration: line-through;
        color: #67718f;
      }

      .view-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 8px;
      }

      .checkbox-row {
        display: inline-flex;
        align-items: center;
        gap: 8px;
      }

      .actions {
        display: inline-flex;
        gap: 6px;
      }

      .actions button {
        padding: 7px 10px;
      }

      .edit-form {
        display: grid;
        gap: 8px;
      }

      .sr-only {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        border: 0;
      }

      @media (max-width: 640px) {
        :host {
          padding: 14px;
        }

        .view-row {
          flex-direction: column;
          align-items: flex-start;
        }
      }
    `,
  ],
})
export class TodoListComponent {
  private nextId = DEFAULT_TODO_STATE.nextId;

  readonly todos = signal<TodoItem[]>(
    DEFAULT_TODO_STATE.todos.map((todo) => ({ ...todo })),
  );

  readonly newTodoControl = new FormControl('', {
    nonNullable: true,
    validators: [Validators.required],
  });

  readonly editControl = new FormControl('', {
    nonNullable: true,
    validators: [Validators.required],
  });

  readonly editingId = signal<number | null>(null);

  readonly totalCount = computed(() => this.todos().length);
  readonly doneCount = computed(
    () => this.todos().filter((todo) => todo.isCompleted).length,
  );
  readonly openCount = computed(() => this.totalCount() - this.doneCount());

  initializeFromState(state?: TodoListState): void {
    if (!state) {
      return;
    }

    const todos = (state.todos ?? []).map((todo) => ({ ...todo }));
    this.todos.set(todos);

    const maxId = todos.reduce((max, todo) => Math.max(max, todo.id), 0);
    this.nextId = Math.max(state.nextId ?? maxId + 1, maxId + 1);

    this.cancelEdit();
    this.newTodoControl.setValue('');
  }

  exportState(): TodoListState {
    return {
      nextId: this.nextId,
      todos: this.todos().map((todo) => ({ ...todo })),
    };
  }

  addTodo(event: Event): void {
    event.preventDefault();

    const title = this.newTodoControl.value.trim();
    if (!title) {
      return;
    }

    this.todos.update((todos) => [
      ...todos,
      {
        id: this.nextId++,
        title,
        isCompleted: false,
      },
    ]);

    this.newTodoControl.setValue('');
  }

  toggleTodo(todoId: number): void {
    this.todos.update((todos) =>
      todos.map((todo) =>
        todo.id === todoId
          ? { ...todo, isCompleted: !todo.isCompleted }
          : todo,
      ),
    );
  }

  startEdit(todo: TodoItem): void {
    this.editingId.set(todo.id);
    this.editControl.setValue(todo.title);
  }

  saveEdit(todoId: number, event: Event): void {
    event.preventDefault();

    const title = this.editControl.value.trim();
    if (!title) {
      return;
    }

    this.todos.update((todos) =>
      todos.map((todo) => (todo.id === todoId ? { ...todo, title } : todo)),
    );

    this.cancelEdit();
  }

  cancelEdit(): void {
    this.editingId.set(null);
    this.editControl.setValue('');
  }

  deleteTodo(todoId: number): void {
    this.todos.update((todos) => todos.filter((todo) => todo.id !== todoId));

    if (this.editingId() === todoId) {
      this.cancelEdit();
    }
  }
}
