// react/src/pages/concepts/viewport/ViewportCenterPage.tsx
import { useRef, useState } from "react";
import {
  KritzelEditor,
  HTMLKritzelEditorElement,
  type KritzelBaseObject,
} from "kritzel-react";
import { reactThemeLight } from "../../../const/react-theme-light";
import {
  buttonStyle,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from "../shared/concept-shared";

export function ViewportCenterPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [objects, setObjects] = useState<KritzelBaseObject<HTMLElement | SVGElement>[]>([]);

  async function onReady() {
    if (!editorRef.current) {
      return;
    }

    await seedEditor(editorRef.current);
    setObjects(((await editorRef.current.getAllObjects()) ?? []) as KritzelBaseObject<HTMLElement | SVGElement>[]);
  }

  async function centerOn(index: number) {
    if (objects[index]) {
      await editorRef.current?.centerObjects([objects[index]]);
    }
  }

  return (
    <div style={hostStyle}>
      <div style={toolbarStyle}>
        <button style={buttonStyle(false)} onClick={() => void centerOn(1)} disabled={objects.length < 2}>Center on Ellipsis</button>
        <button style={buttonStyle(false)} onClick={() => void centerOn(0)} disabled={objects.length === 0}>Center on Rectangle</button>
        <button style={buttonStyle(false)} onClick={() => void centerOn(2)} disabled={objects.length < 3}>Center on Line</button>
        <button style={buttonStyle(false)} onClick={() => void centerOn(3)} disabled={objects.length < 4}>Center on Path</button>
        <button style={buttonStyle(false)} onClick={() => void editorRef.current?.backToContent()}>Back to Content</button>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="viewport-center"
        theme="react-theme"
        themes={[reactThemeLight]}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          void onReady();
        }}
        style={editorStyle}
      />
    </div>
  );
}

// vue/src/pages/concepts/viewport/ViewportCenterPage.vue
<script setup lang="ts">

import { KritzelEditor } from 'kritzel-vue'
import { vueThemeLight } from '../../../const/vue-theme-light'
import {
  buttonStyle,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
  getEditorRef,
} from '../shared/concept-shared'
import { ref } from 'vue';

type ObjectItem = Parameters<HTMLKritzelEditorElement['centerObjects']>[0][number]

const editor = getEditorRef('editor');
const objects = ref<ObjectItem[]>([])

async function onReady() {
  if (!editor.value) {
    return
  }

  await seedEditor(editor.value)
  objects.value = ((await editor.value.getAllObjects()) ?? []) as ObjectItem[]
}

async function centerOn(index: number) {
  const target = objects.value[index]
  if (target) {
    await editor.value?.centerObjects([target] as unknown as Parameters<HTMLKritzelEditorElement['centerObjects']>[0])
  }
}
</script>

<template>
  <div :style="hostStyle">
    <div :style="toolbarStyle">
      <button :style="buttonStyle(false)" :disabled="objects.length < 2" @click="centerOn(1)">Center on Ellipsis</button>
      <button :style="buttonStyle(false)" :disabled="objects.length === 0" @click="centerOn(0)">Center on Rectangle</button>
      <button :style="buttonStyle(false)" :disabled="objects.length < 3" @click="centerOn(2)">Center on Line</button>
      <button :style="buttonStyle(false)" :disabled="objects.length < 4" @click="centerOn(3)">Center on Path</button>
      <button :style="buttonStyle(false)" @click="editor?.backToContent()">Back to Content</button>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="viewport-center"
      theme="vue-theme"
      :themes="[vueThemeLight]"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>
