// vue/src/pages/concepts/tools/ToolsDisablePage.vue
<script setup lang="ts">

import { KritzelEditor } from 'kritzel-vue'
import { vueThemeLight } from '../../../const/vue-theme-light'
import {
  buttonStyle,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
  getEditorRef,
} from '../shared/concept-shared'
import { ref } from 'vue';

const editor = getEditorRef('editor');
const isDisabled = ref(true)

async function onReady() {
  if (!editor.value) {
    return
  }

  await seedEditor(editor.value)
  await editor.value.disable()
}

async function toggle() {
  if (!editor.value) {
    return
  }

  if (isDisabled.value) {
    await editor.value.enable()
    isDisabled.value = false
    return
  }

  await editor.value.disable()
  isDisabled.value = true
}
</script>

<template>
  <div :style="hostStyle">
    <div :style="toolbarStyle">
      <button :style="buttonStyle(false)" @click="toggle">
        {{ isDisabled ? 'Enable' : 'Disable' }}
      </button>
      <span :style="{ fontSize: '13px', color: isDisabled ? '#e53935' : '#333' }">
        {{ isDisabled ? 'Interactions disabled' : 'Interactions enabled' }}
      </span>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="tools-disable"
      theme="light"
      :themes="[vueThemeLight]"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>

// react/src/pages/concepts/tools/ToolsDisablePage.tsx
import { useRef, useState } from "react";
import {
  KritzelEditor,
  HTMLKritzelEditorElement,
} from "kritzel-react";
import { reactThemeLight } from "../../../const/react-theme-light";
import {
  buttonStyle,
  editorStyle,
  hostStyle,
  seedEditor,
  toolbarStyle,
} from "../shared/concept-shared";

export function ToolsDisablePage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [isDisabled, setIsDisabled] = useState(true);

  async function onReady() {
    if (!editorRef.current) {
      return;
    }

    await seedEditor(editorRef.current);
    await editorRef.current.disable();
  }

  async function toggle() {
    if (!editorRef.current) {
      return;
    }

    if (isDisabled) {
      await editorRef.current.enable();
      setIsDisabled(false);
      return;
    }

    await editorRef.current.disable();
    setIsDisabled(true);
  }

  return (
    <div style={hostStyle}>
      <div style={toolbarStyle}>
        <button style={buttonStyle(false)} onClick={() => void toggle()}>
          {isDisabled ? "Enable" : "Disable"}
        </button>
        <span style={{ fontSize: "13px", color: isDisabled ? "#e53935" : "#333" }}>
          {isDisabled ? "Interactions disabled" : "Interactions enabled"}
        </span>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="tools-disable"
        theme="light"
        themes={[reactThemeLight]}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          void onReady();
        }}
        style={editorStyle}
      />
    </div>
  );
}
