// vue/src/pages/examples/CustomToolbar1Page.vue
<script setup lang="ts">
import {
  KritzelEditor,
  KritzelBrushTool,
  KritzelSelectionTool,
  KritzelToolbarControl,
} from 'kritzel-vue'

const controls: KritzelToolbarControl[] = [
  { type: 'tool', tool: KritzelSelectionTool, name: 'Select', icon: 'cursor', isDefault: true },
  { type: 'tool', tool: KritzelBrushTool, name: 'Brush', icon: 'pen' },
]
</script>

<template>
  <main>
    <KritzelEditor :controls="controls" />
  </main>
</template>

<style scoped></style>

// react/src/pages/examples/CustomToolbar1Page.tsx
import {
  KritzelEditor,
  KritzelBrushTool,
  KritzelSelectionTool,
  KritzelToolbarControl,
} from "kritzel-react";

const controls: KritzelToolbarControl[] = [
  { type: "tool", tool: KritzelSelectionTool, name: "Select", icon: "cursor", isDefault: true },
  { type: "tool", tool: KritzelBrushTool, name: "Brush", icon: "pen" },
];

export function CustomToolbar1Page() {
  return (
    <div className="app">
      <KritzelEditor controls={controls} />
    </div>
  );
}
