// vue/src/pages/getting-started/QuickstartPage.vue
<script setup lang="ts">
import { getEditorRef, KritzelEditor } from 'kritzel-vue'
import { customVueTheme } from '../../const/custom-vue-theme'
import { seedEditor } from '../concepts/shared/concept-shared';

const editor = getEditorRef('editor');

async function onReady() {
    if (editor.value) {
        await seedEditor(editor.value)
    }
}

</script>

<template>
    <div class="host">
        <KritzelEditor
            ref="editor"
            editorId="quickstart"
            theme="vue-theme"
            :themes="[customVueTheme]"
            :isPanningEnabled="false"
            :isZoomingEnabled="false"
            :isMoreMenuVisible="false"
            :isWorkspaceManagerVisible="false"
            @isReady="onReady"
        />
    </div>
</template>

<style scoped>
.host {
    display: block;
    height: 100%;
}
</style>

// react/src/pages/getting-started/QuickstartPage.tsx
import { CSSProperties, useCallback, useRef } from "react";
import { KritzelEditor } from "kritzel-react";
import { customReactTheme } from "../../const/custom-react-theme";
import { seedEditor } from "../concepts/shared/concept-shared";

const hostStyle: CSSProperties = {
  display: "block",
  height: "100%",
};

export function QuickstartPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);

  const onReady = useCallback(async () => {
    if (editorRef.current) {
      await seedEditor(editorRef.current);
    }
  }, []);

  return (
    <div style={hostStyle}>
      <KritzelEditor
        ref={editorRef}
        editorId="quickstart"
        theme="react-theme"
        themes={[customReactTheme]}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={onReady}
      />
    </div>
  );
}
